all: ques1

ques1:
	clang++ -std=c++11 -stdlib=libc++ ques1.cpp -o ques1

ques2:
	clang++ -std=c++11 -stdlib=libc++ ques2.cpp -o ques2

ques3:
	g++ ques3.cpp -o ques3 

clean:
	rm -rf *.o ques3 ques2 ques1
